[opener]
open = [
  { run = 'xdg-open "$1"', desc = "Open", orphan = true, for = "linux" }
]

[open]
prepend_rules = [
  { mime = "text/html", use = "open" },
  { mime = "application/xhtml+xml", use = "open" }
]
